
import React, { useState } from 'react';
import { SEOInput, SEOPackage } from './types';
import { generateSEOPackage, generateThumbnailImage } from './services/geminiService';
import InputForm from './components/InputForm';
import ResultCard from './components/ResultCard';

const App: React.FC = () => {
  const [input, setInput] = useState<SEOInput>({
    userContent: '',
    userLanguage: 'Sindhi',
    channelName: '',
    targetCountry: 'Pakistan',
    videoType: 'Education',
    preferredUploadTime: '',
  });
  const [result, setResult] = useState<SEOPackage | null>(null);
  const [thumbnailUrl, setThumbnailUrl] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [loadingImage, setLoadingImage] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [copiedAll, setCopiedAll] = useState(false);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    setInput(prev => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError(null);
    setResult(null);
    setThumbnailUrl(null);
    setCopiedAll(false);
    
    try {
      const data = await generateSEOPackage(input);
      setResult(data);
      setLoading(false);
    } catch (err: any) {
      setError(err.message || 'Something went wrong.');
      setLoading(false);
    }
  };

  const handleGenerateThumbnail = async () => {
    if (!result) return;
    setLoadingImage(true);
    setError(null);
    try {
      const imageUrl = await generateThumbnailImage(result.thumbnailAIPrompt);
      setThumbnailUrl(imageUrl);
    } catch (imgErr: any) {
      setError("Failed to generate thumbnail image.");
    } finally {
      setLoadingImage(false);
    }
  };

  const handleCopyAll = () => {
    if (!result) return;
    
    const content = `
TUBEEXPERT PRO - FULL YOUTUBE SEO PACKAGE (DEC 2025)
--------------------------------------------------
Topic: ${input.userContent}
Channel: ${input.channelName}

1. TITLES
----------
Main Title: ${result.title}
Romanized Title: ${result.titleRoman}

2. DESCRIPTIONS
---------------
ENGLISH VERSION:
${result.descriptionEnglish}

NATIVE VERSION (${input.userLanguage}):
${result.descriptionNative}

ROMANIZED VERSION:
${result.descriptionRoman}

3. TAXONOMY (TAGS & HASHTAGS)
----------------------------
Hashtags: ${result.hashtags.join(' ')}
Viral Tags: ${result.tagsEnglish.join(', ')}
Romanized Tags: ${result.tagsRoman.join(', ')}

4. ALGORITHM OPTIMIZATION
-------------------------
Viral Hack Strategy: ${result.algorithmBoostStrategy.viralHack110}
Long-Tail Keywords: ${result.hashtagOptimization.longTailHashtags.join(', ')}
Niche Clusters: ${result.hashtagOptimization.nicheHashtags.join(', ')}
Redundancy Report: ${result.hashtagOptimization.redundancyReport}
Suggested Replacements: ${result.hashtagOptimization.suggestedReplacements.join(', ')}

5. ENGAGEMENT VELOCITY
----------------------
Optimal Upload Time: ${result.algorithmBoostStrategy.bestUploadTime}
Pinned Comment Hook: ${result.algorithmBoostStrategy.pinnedComment}
Engagement Bait: ${result.algorithmBoostStrategy.engagementBait}
Keyword Strategy: ${result.algorithmBoostStrategy.keywordStrategy}
A/B Test Plan: ${result.algorithmBoostStrategy.abTesting}

6. THUMBNAIL TEXT HACKS
-----------------------
Native Script: ${result.thumbnailTextNative.join(' | ')}
Roman Script: ${result.thumbnailTextRoman.join(' | ')}

Generated by TubeExpert Pro - 110% Reach Enabled
    `.trim();

    navigator.clipboard.writeText(content);
    setCopiedAll(true);
    setTimeout(() => setCopiedAll(false), 2000);
  };

  return (
    <div className="min-h-screen bg-[#0f0f0f] text-white selection:bg-red-500/30">
      <header className="sticky top-0 z-50 bg-[#0f0f0f]/80 backdrop-blur-md border-b border-zinc-800 no-print">
        <div className="max-w-7xl mx-auto px-4 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 bg-red-600 rounded-lg flex items-center justify-center shadow-lg shadow-red-600/20">
              <svg viewBox="0 0 24 24" className="w-5 h-5 fill-white"><path d="M10 15l5.19-3L10 9v6m11.56-7.83c.13.47.22 1.1.28 1.9.07.8.1 1.49.1 2.09L22 12c0 .6-.03 1.29-.1 2.09-.06.8-.15 1.43-.28 1.9-.13.47-.29.85-.48 1.14-.19.29-.41.51-.66.67-.25.16-.54.27-.87.33-.33.06-.75.09-1.26.1-1.01.02-2.31.02-3.89.02-1.58 0-2.88 0-3.89-.02-.51-.01-.93-.04-1.26-.1-.33-.06-.62-.17-.87-.33-.25-.16-.47-.38-.66-.67-.19-.29-.35-.67-.48-1.14-.13-.47-.22-1.1-.28-1.9-.07-.8-.1-1.49-.1-2.09L2 12c0-.6.03-1.29.1-2.09.06-.8.15-1.43.28-1.9.13-.47.29-.85.48-1.14.19-.29.41-.51.66-.67.25-.16.54-.27.87-.33.33-.06.75-.09 1.26-.1 1.01-.02 2.31-.02 3.89-.02 1.58 0 2.88 0 3.89.02.51.01.93.04 1.26.1.33.06.62.17.87.33.25.16.47.38.66.67.19.29.35.67.48 1.14z"/></svg>
            </div>
            <span className="font-bold text-xl tracking-tight">TubeExpert <span className="text-red-600">Pro</span></span>
          </div>
          <div className="flex items-center gap-2 px-3 py-1 bg-zinc-800 rounded-full border border-zinc-700">
             <div className="w-2 h-2 bg-red-500 rounded-full animate-pulse"></div>
             <span className="text-[10px] font-black text-zinc-400 uppercase tracking-widest">VIRAL ENGINE: 110% READY</span>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-4 py-8">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
          <div className="lg:col-span-4 space-y-6 no-print">
            <h1 className="text-3xl font-extrabold tracking-tight">Algorithm <span className="text-red-500 underline decoration-red-500/20 decoration-4 underline-offset-4">Full Hack</span></h1>
            <InputForm 
              input={input} 
              onChange={handleInputChange} 
              onSubmit={handleSubmit} 
              onGenerateThumbnail={handleGenerateThumbnail}
              loading={loading}
              loadingImage={loadingImage}
              canGenerateThumbnail={!!result}
            />
            {error && <div className="p-4 bg-red-900/20 border border-red-900/50 rounded-lg text-red-500 text-sm flex items-center gap-2">
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
              {error}
            </div>}
          </div>

          <div className="lg:col-span-8">
            {result ? (
              <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
                
                {/* Global Toolkit Controls */}
                <div className="flex flex-wrap items-center justify-between gap-4 p-5 bg-zinc-900/80 backdrop-blur-md border border-zinc-800 rounded-2xl no-print shadow-xl">
                  <div className="flex items-center gap-3">
                    <div className="w-2 h-2 bg-green-500 rounded-full animate-ping"></div>
                    <span className="text-xs font-black text-zinc-400 uppercase tracking-widest">Package Status: SEO HACKED</span>
                  </div>
                  <div className="flex gap-2">
                    <button 
                      onClick={handleCopyAll}
                      className={`px-5 py-2.5 rounded-xl text-sm font-bold transition-all border flex items-center gap-2 ${copiedAll ? 'bg-green-600/10 text-green-500 border-green-500/50' : 'bg-red-600 hover:bg-red-500 text-white shadow-lg shadow-red-600/20'}`}
                    >
                      <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3" /></svg>
                      {copiedAll ? 'COPIED FULL PACKAGE' : 'COPY ALL TEXT'}
                    </button>
                    <button onClick={() => window.print()} className="px-5 py-2.5 bg-zinc-800 hover:bg-zinc-700 text-zinc-300 rounded-xl text-sm font-bold border border-zinc-700 transition-all">
                      EXPORT PDF
                    </button>
                  </div>
                </div>

                {/* 1. Growth Strategy & Hacks */}
                <section className="space-y-4">
                  <h2 className="text-xs font-black text-zinc-500 uppercase tracking-[0.3em] ml-1">Algorithm Loop Strategy</h2>
                  <div className="grid grid-cols-1 gap-4">
                    <ResultCard title="110% REACH VIRAL HACK (DEC 2025)" content={result.algorithmBoostStrategy.viralHack110} />
                    
                    <div className="bg-zinc-900 border border-zinc-800 rounded-2xl overflow-hidden shadow-lg">
                      <div className="px-4 py-3 bg-zinc-800/50 flex justify-between items-center border-b border-zinc-700">
                        <h3 className="text-xs font-black text-zinc-400 uppercase tracking-widest">Relevance Predictor Score</h3>
                        <span className="text-[10px] bg-red-600/20 text-red-500 px-2 py-0.5 rounded-full font-bold">LIVE METRIC</span>
                      </div>
                      <div className="p-5 grid grid-cols-1 sm:grid-cols-2 gap-6">
                        {result.hashtagScores.map((hs, idx) => (
                          <div key={idx} className="space-y-2">
                            <div className="flex justify-between items-center text-sm">
                              <span className="font-bold text-red-500">#{hs.tag}</span>
                              <span className="text-zinc-500 text-xs font-mono">{hs.score}%</span>
                            </div>
                            <div className="h-2 w-full bg-zinc-800 rounded-full overflow-hidden">
                              <div 
                                className={`h-full rounded-full transition-all duration-1000 ${hs.score > 80 ? 'bg-red-600' : hs.score > 50 ? 'bg-orange-500' : 'bg-zinc-600'}`}
                                style={{ width: `${hs.score}%` }}
                              />
                            </div>
                            <p className="text-[10px] text-zinc-400 font-medium italic leading-tight">{hs.impact}</p>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                </section>

                {/* 2. Metadata: Titles & Descriptions */}
                <section className="space-y-4">
                  <h2 className="text-xs font-black text-zinc-500 uppercase tracking-[0.3em] ml-1">Metadata Core</h2>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <ResultCard title="SEO PRIMARY TITLE" content={result.title} />
                    <ResultCard title="ROMANIZED TITLE" content={result.titleRoman} />
                  </div>
                  <div className="grid grid-cols-1 gap-4">
                    <ResultCard title="HACKED DESCRIPTION (ENGLISH)" content={result.descriptionEnglish} />
                    <ResultCard title={`NATIVE DESCRIPTION (${input.userLanguage})`} content={result.descriptionNative} />
                    <ResultCard title="ROMANIZED DESCRIPTION" content={result.descriptionRoman} />
                  </div>
                </section>

                {/* 3. Taxonomy: Tags & Hashtags */}
                <section className="space-y-4">
                  <h2 className="text-xs font-black text-zinc-500 uppercase tracking-[0.3em] ml-1">Taxonomy & Indexing</h2>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <ResultCard title="VIRAL TAGS (COPY/PASTE)" content={result.tagsEnglish} isList />
                    <ResultCard title="PRIMARY HASHTAGS" content={result.hashtags} isList />
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <ResultCard title="ROMANIZED TAGS" content={result.tagsRoman} isList />
                    <ResultCard title="OPTIMAL UPLOAD WINDOW" content={result.algorithmBoostStrategy.bestUploadTime} />
                  </div>
                </section>

                {/* 4. Optimization Reports */}
                <section className="space-y-4">
                  <h2 className="text-xs font-black text-zinc-500 uppercase tracking-[0.3em] ml-1">SEO Optimization Report</h2>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <ResultCard title="LONG-TAIL KEYWORDS" content={result.hashtagOptimization.longTailHashtags} isList />
                    <ResultCard title="NICHE TOPIC CLUSTERS" content={result.hashtagOptimization.nicheHashtags} isList />
                  </div>
                  <div className="grid grid-cols-1 gap-4">
                    <ResultCard title="REDUNDANCY ANALYSIS" content={result.hashtagOptimization.redundancyReport} />
                    <ResultCard title="SUGGESTED REPLACEMENTS" content={result.hashtagOptimization.suggestedReplacements} isList />
                  </div>
                </section>

                {/* 5. Engagement Velocity Strategy */}
                <section className="space-y-4">
                  <h2 className="text-xs font-black text-zinc-500 uppercase tracking-[0.3em] ml-1">Engagement Velocity</h2>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <ResultCard title="PINNED COMMENT HOOK" content={result.algorithmBoostStrategy.pinnedComment} />
                    <ResultCard title="ENGAGEMENT BAIT TRIGGER" content={result.algorithmBoostStrategy.engagementBait} />
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <ResultCard title="KEYWORD VELOCITY PLAN" content={result.algorithmBoostStrategy.keywordStrategy} />
                    <ResultCard title="A/B TESTING VARIATIONS" content={result.algorithmBoostStrategy.abTesting} />
                  </div>
                </section>

                {/* 6. Thumbnail Preview & Text Hacks */}
                <section className="space-y-4">
                  <h2 className="text-xs font-black text-zinc-500 uppercase tracking-[0.3em] ml-1">Visual Optimization</h2>
                  <div className="bg-zinc-900 border border-zinc-800 rounded-3xl overflow-hidden shadow-2xl relative aspect-video flex items-center justify-center group">
                    {thumbnailUrl ? (
                      <>
                        <img src={thumbnailUrl} className="w-full h-full object-cover" alt="Viral Thumbnail" />
                        <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center no-print">
                           <button onClick={handleGenerateThumbnail} className="bg-white text-black px-4 py-2 rounded-lg font-bold text-xs">REGENERATE 8K</button>
                        </div>
                      </>
                    ) : (
                      <div className="flex flex-col items-center gap-4 p-8 text-center">
                        <div className="w-16 h-16 bg-zinc-800 rounded-full flex items-center justify-center animate-pulse">
                          <svg className="w-8 h-8 text-zinc-600" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" /></svg>
                        </div>
                        <p className="text-zinc-600 text-xs font-bold uppercase tracking-widest">Awaiting Visual Seed...</p>
                        {loadingImage && <span className="text-red-500 text-[10px] font-black animate-pulse">RENDERING HDR MATRIX...</span>}
                      </div>
                    )}
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <ResultCard title="NATIVE THUMBNAIL OVERLAYS" content={result.thumbnailTextNative.join(' | ')} />
                    <ResultCard title="ROMAN THUMBNAIL OVERLAYS" content={result.thumbnailTextRoman.join(' | ')} />
                  </div>
                </section>
                
              </div>
            ) : loading ? (
              <div className="h-full min-h-[600px] flex flex-col items-center justify-center p-12 space-y-8 no-print">
                <div className="relative w-32 h-32">
                  <div className="absolute inset-0 border-8 border-zinc-800 rounded-full"></div>
                  <div className="absolute inset-0 border-8 border-red-600 rounded-full border-t-transparent animate-spin"></div>
                  <div className="absolute inset-4 border-4 border-orange-500/20 rounded-full animate-pulse"></div>
                </div>
                <div className="text-center space-y-3">
                   <h3 className="text-2xl font-black text-white tracking-tight animate-pulse">Calculating Viral Velocity...</h3>
                   <p className="text-zinc-500 text-sm max-w-sm mx-auto">Accessing December 2025 YouTube recommendation clusters for {input.userLanguage} content.</p>
                </div>
              </div>
            ) : (
              <div className="h-full min-h-[600px] flex flex-col items-center justify-center text-center p-12 border-2 border-dashed border-zinc-800 rounded-[2.5rem] opacity-40 hover:opacity-60 transition-opacity group no-print">
                <div className="w-20 h-20 bg-zinc-900 rounded-full flex items-center justify-center mb-6 group-hover:scale-110 transition-transform duration-500">
                   <svg className="w-10 h-10 text-red-600 animate-bounce" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                     <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                   </svg>
                </div>
                <h3 className="text-xl font-black text-zinc-400 mb-2 uppercase tracking-widest">Topic Cluster Waiting</h3>
                <p className="text-sm text-zinc-600 max-w-xs leading-relaxed">Input your video data to bypass standard recommendation filters and force 110% reach.</p>
              </div>
            )}
          </div>
        </div>
      </main>

      <footer className="mt-20 border-t border-zinc-800 py-12 no-print bg-zinc-900/20 backdrop-blur-sm">
        <div className="max-w-7xl mx-auto px-4 text-center">
          <p className="text-[10px] font-black text-zinc-700 uppercase tracking-[0.5em] mb-4">Proprietary Algorithm Bypass Engine</p>
          <div className="text-xs text-zinc-500 font-medium">
            © 2024 TubeExpert Pro. Optimized for Dec 2025 YouTube core updates. Use responsibly to scale your digital presence.
          </div>
        </div>
      </footer>
    </div>
  );
};

export default App;
